Icon, custom build folders and README updated
mumble-voip/mumble-pahelper pull request #11
Opened 2016-10-16 20:46 UTC by davidebeatrici

- Icon/Logo for the window title and Windows executable.
- README updated with logo, default paths and new screenshots.
- Build and Debug folders inside the project directory.
- Build files in separated folders.

2016-10-18 17:36 UTC, Kissaki commented on README.md
> +<p align="center"><img src = "resources/MumblePAHelper.png"/></p>
Why did you use HTML rather than Markdown?

2016-10-18 17:36 UTC, Kissaki commented on MumblePAHelper.pro
> +DESTDIR = $$DESTDIR
Does this do anything?

2016-10-18 17:36 UTC, Kissaki commented on README.md
> +You can use this tool to quickly see if your plugin is working as it should.<br>
I would rather not have `<br>`s in a markdown README file.

2016-10-18 17:36 UTC, Kissaki commented on README.md
> +Mumble Positional Audio Helper is a small tool for testing the functionality of positional audio plugins outside of Mumble.
Why did you change from limited line length to everything in one line?

While we could debate if our [Coding Guidelines](http://wiki.mumble.info/wiki/Coding_Guidelines) apply here in a markdown readme, we limit lines to 100 characters in our C++ code. Markdown will ignore the newline, and render the result with adequate newlines anyway (at least that is what I expect).

2016-10-18 17:36 UTC, Kissaki commented on README.md
> +## Default paths
What about adding a note "You can find existing plugins in these folders" to indicate this is not where he has to place the PAHelper/his plugins to test?

Or did you mean to give these as a hint where to place them *after* testing with PAHelper?

2016-10-18 17:36 UTC, Kissaki commented on README.md
> +![Screenshot on Linux](resources/screenshot_linux.png)
I was thinking about whether we need two screenshots just now. But I guess its reasonable.

2016-10-18 17:44 UTC, davidebeatrici commented on README.md
> +![Screenshot on Linux](resources/screenshot_linux.png)
It's just to show that it works and how it is on both Windows and Linux.

2016-10-18 18:07 UTC, davidebeatrici commented on README.md
> +<p align="center"><img src = "resources/MumblePAHelper.png"/></p>
You can't center images with the Markdown.
http://stackoverflow.com/questions/12090472/github-readme-md-center-image

2016-10-18 18:09 UTC, davidebeatrici commented on MumblePAHelper.pro
> +DESTDIR = $$DESTDIR
No, it doesn't, I removed it.

2016-10-18 18:09 UTC, davidebeatrici commented on README.md
> +## Default paths
I added the note. :wink:

2016-10-18 18:09 UTC, davidebeatrici commented on README.md
> +Mumble Positional Audio Helper is a small tool for testing the functionality of positional audio plugins outside of Mumble.
Done. :wink:

2016-10-18 22:24 UTC, Kissaki commented on README.md
> +<p align="center"><img src = "resources/MumblePAHelper.png"/></p>
I would not introduce HTML for that then. We don’t (_really_) need it to be centred. It’s a markdown file after all.

2016-10-18 22:32 UTC, Kissaki commented on README.md
> +Simply place it next to your plugin and launch it.
As this logically continues the last sentence, it should be one paragraph after all. Or rewritten.

Actually, with the intro paragraph before, the previous does not really add much anyway.

> To test your Plugin place it next to PAHelper executable and launch it.

2016-10-18 22:33 UTC, Kissaki commented
Apart from these two, LGTM.

2016-10-19 13:03 UTC, davidebeatrici commented on README.md
> +<p align="center"><img src = "resources/MumblePAHelper.png"/></p>
You're right.
I replaced it with the Markdown. :wink:

2016-10-19 13:17 UTC, davidebeatrici commented on README.md
> +Simply place it next to your plugin and launch it.
I think that we should remove it, because "Include plugins from current directory" explains itself.

2016-10-19 17:01 UTC, Kissaki commented on README.md
> +Simply place it next to your plugin and launch it.
Did you want to change this? It still refers to the previous sentence, which is in a different paragraph.

2016-10-19 17:26 UTC, davidebeatrici commented on README.md
> +Simply place it next to your plugin and launch it.
I don't know if it's better to remove it, put the sentence in the same paragraph or use yours...

2016-10-19 17:58 UTC, mkrautz requested changes

2016-10-19 17:58 UTC, mkrautz commented on MumblePAHelper.pro
> +Release: DESTDIR = $$_PRO_FILE_PWD_/release
Usually we use "release" and "debug"... I think they're case sensitive?

2016-10-19 18:13 UTC, davidebeatrici commented on MumblePAHelper.pro
> +Release: DESTDIR = $$_PRO_FILE_PWD_/release
Yes, they are, because a strange thing happens.

If I use **Release** and **Debug** the files are correctly separated, but QMake creates the empty folders ".moc" and ".ui" in the root of my drive.
If I use **release** and **debug**, QMake doesn't create the empty folders, but **ui_mumblepahelper.h** is in the "debug" folder instead of the "release" one.
The ".ui" folder isn't even created in the "release" one.

2016-10-19 19:32 UTC, mkrautz commented on MumblePAHelper.pro
> +Release: DESTDIR = $$_PRO_FILE_PWD_/release
Have you tried using the pattern that Mumble itself uses?
It does:

	CONFIG(debug, debug|release) {
	  CONFIG += console
	  QMAKE_LIBDIR += ../../debug
	  DESTDIR	= ../../debug
	}

	CONFIG(release, debug|release) {
	  QMAKE_LIBDIR += ../../release
	  DESTDIR	= ../../release
	}

2016-10-19 19:33 UTC, mkrautz commented on MumblePAHelper.pro
> +Release: DESTDIR = $$_PRO_FILE_PWD_/release
(You'd probably use `DESTDIR = $$_PRO_FILE_PWD_/release`, and s/release/debug, etc.)

2016-10-19 20:39 UTC, davidebeatrici commented on MumblePAHelper.pro
> +Release: DESTDIR = $$_PRO_FILE_PWD_/release
For some reason **ui_mumblepahelper.h** is still in the debug folder.

2016-10-20 14:03 UTC, davidebeatrici commented on MumblePAHelper.pro
> +Release: DESTDIR = $$_PRO_FILE_PWD_/release
Now for some reason it works, I committed the change. :wink:

2016-10-20 14:36 UTC, Kissaki approved these changes

2016-10-20 14:36 UTC, Kissaki commented on MumblePAHelper.pro
> +  CONFIG += console
Confusing, but I guess our working practice. :)

2016-10-23 20:27 UTC, mkrautz commented
LGTM

2016-10-23 20:27 UTC, mkrautz approved these changes

2016-10-23 20:27 UTC, merged